# -*- coding: utf-8 -*-
"""Sheet 3 — Translate (still-empty rows) and Sheet 4 — the generation rules."""

# key, where it appears, note for the translator (slots etc.), kind for grouping
TRANSLATE_WHERE = {
    "ui000": ("A hidden link at the very top of the page, read out by screen readers (“Skip to report”).", ""),
    "ui001": ("A yellow banner shown only on internal review copies of the report — never on a school’s copy.", ""),
    "ui004": ("A short button label used on narrow screens (phones) instead of “Clear all filters”, which is already translated as “Clirio pob hidlydd”.", "Keep it short — it is one small button."),
    "ui005": ("The cover page — the line above the school’s name.", ""),
    "ui032": ("Guide page (“How to use this report”) — the sentence under the heading.", ""),
    "ui054": ("Guide page — an EXAMPLE of the “You are viewing” banner, showing what it looks like when filters are on. The words are an illustration, not live data.", "“Year 5”, “Boys” and “Football” are examples; translate them as they appear elsewhere (Blwyddyn 5 · Bechgyn · Wedi dewis Pêl droed). The “·” separators stay."),
    "ui055": ("Guide page — the second line of the same example banner.", "“7” stays as a figure."),
    "ui183": ("The footer line at the bottom of every page, and the print footer.", ""),
    "ui185": ("A note shown only on internal review copies (about provisional summary wording).", ""),
    "ui186": ("A small label (“kicker”) above the “Next steps” section heading.", "One or two words."),
    "ui187": ("The heading of the “Next steps” section.", ""),
    "ui188": ("A small label above the “Thank you” section heading.", "One or two words."),
    "ui189": ("The heading of the “Thank you” section.", ""),
    "ui195": ("A small label above the Appendix section heading.", "One word."),
    "ui200": ("The label of the collapsible technical record at the end of the appendix.", ""),
    "ui225": ("The label above the written explanation under a table (“What is this table showing?”). The chart version (“What is this chart showing?”) is already translated: “Beth mae’r siart hon yn ei ddangos?”", "Please match the chart version."),
    "ui226": ("The label above the written explanation under a pair of charts.", "Please match ui225."),
    "ui227": ("The label above the written explanation under a section.", "Please match ui225."),
    "ui228": ("A sub-heading inside an explanation: the part of the explanation that goes year by year.", "Two words."),
    "ui230": ("A note under the stacked chart of sports and how often pupils do them.", ""),
    "ui247": ("A chart heading naming the “Somewhere Else” setting, with its explanation in brackets. The survey answer option is “Rhywle arall”.", "Keep “Rhywle arall” for “Somewhere Else”."),
    "ui.aria_cover": ("Not visible — the name a screen reader gives the cover page.", ""),
    "ui.aria_toc": ("Not visible — the name a screen reader gives the list of report sections in the side panel.", ""),
    "ui.nav_aria": ("Not visible — the name a screen reader gives the Back / Contents / Next links.", ""),
    "ui.chart_sports_total_club": ("The note under the chart of sports done in a school sports club. The same sentence for PE lessons is already translated (see the row above it in the workbook).", "{n} is replaced by a number (the number of sports in the list). Keep {n} exactly as it is."),
    "ui.chart_sports_total_community": ("The note under the chart of sports done in a club outside of school.", "Keep {n} exactly."),
    "ui.chart_sports_total_other": ("The note under the chart of sports done somewhere else.", "Keep {n} exactly."),
    "ui.doc_title": ("The title shown on the browser tab.", "{school} is replaced by the school’s name. Keep {school} exactly."),
    "ui.fsm_context_title": ("The title of the small card about Free School Meals on the “Who took part” page. (Sport Wales may still change the English of this card; please translate what is here.)", ""),
    "ui.fsm_context_body": ("The text of the same card.", "{value} is replaced by the school’s figure. Keep {value} exactly, at the end."),
    "ui.fsm_context_value": ("The placeholder shown where the figure will go until it is supplied.", ""),
    "ui.meta_survey_year": ("A row label in the technical record table.", ""),
    "ui.meta_report_version": ("A row label in the technical record table.", ""),
    "ui.meta_version_value": ("The value shown beside “Report version”.", "{report} and {schema} are replaced by version codes. Keep both exactly; only “schema” may be translated if there is a Welsh term."),
    "ui.meta_pipeline": ("A row label in the technical record table.", ""),
    "ui.meta_suppression": ("A row label in the technical record table (the rule that hides small groups).", ""),
    "ui.meta_generated": ("A row label in the technical record table (the date the report was produced).", ""),
    "ui.meta_checksum": ("A row label in the technical record table (a technical fingerprint of the data file).", ""),
    "ui.meta_weighting": ("A row label in the technical record table.", ""),
    "ui.meta_weighting_value": ("The value shown beside “Weighting”: the results are raw counts, not weighted.", ""),
    "ui.review_note": ("A note shown only on internal review copies, in the side panel, reporting how much of the page text is in Welsh.", "{done}, {total} and {pending} are replaced by numbers. Keep all three exactly."),
    "responses_by_gender_base_note": ("A footnote under the chart “How many pupils responded?” (by gender).", ""),
    "ethnicity_group_base_note": ("A footnote under the ethnicity table.", "“Other ethnic groups” is the survey’s answer option: “Grwpiau ethnig eraill”."),
    "dl_combined": ("The name of a filter group in the “Pupil group” dropdown (pupils who said yes to either the disability question or the learning-difficulty question).", ""),
    "ed_combined": ("The name of a filter group in the “Pupil group” dropdown.", "“(combined filter group)” explains that it is built from the ethnicity question; keep a short bracketed note."),
    "ws_combined": ("The name of a filter group in the “Pupil group” dropdown (pupils who said they speak Welsh very well, a fair amount or a little).", ""),
    "settings_dl": ("A chart heading in the disability section.", ""),
    "settings_dy": ("A chart heading (the group shown in the chart).", "Please use the same term for “long-term condition” as you choose on sheet 2 (row disability_condition)."),
    "settings_ly": ("A chart heading (the group shown in the chart).", ""),
    "h2_generic_reflect": ("One of the discussion questions offered to the school at the end of a chapter (“What your findings may help you explore”).", ""),
    "h2_generic_discussion": ("Another discussion question at the end of a chapter.", ""),
    "ui.gdpr_body_full": ("The message shown in place of the whole report when a filter selects fewer than five pupils. It refers to data-protection law (GDPR); please translate faithfully.", ""),
    "ui.gdpr_body_module": ("The message shown in place of one section when a group in that section has fewer than five pupils.", ""),
    "ui.a11y_switch": ("The label of the new “Accessibility features” switch in the side panel (it turns on larger text, higher contrast and colour-blind-safe charts).", "Short — it is a switch label."),
    "ui.a11y_glossary_heading": ("The heading of the glossary panel shown on the guide page when the accessibility switch is on.", ""),
    "ui.a11y_glossary_intro": ("The line under that heading.", ""),
}
TRANSLATE_EXTRA_EN = {
    "h2_generic_reflect": "Which findings match what you see day to day, and which are surprising?",
    "h2_generic_discussion": "Could further pupil discussion help explain these findings before provision changes are planned?",
    "responses_by_gender_base_note": "Every response option is shown, including options selected by no pupils, so the bars sum exactly to the base.",
    "ethnicity_group_base_note": "Categories selected by fewer than five respondents across the whole school are combined into \"Other ethnic groups\" to protect individual pupils.",
    "ui.gdpr_body_full": "Fewer than five pupils match this selection, so their results are suppressed to protect pupil identity, in line with GDPR. The greyed charts show the whole school for context. Broaden the selection to see this group’s findings.",
    "ui.gdpr_body_module": "Fewer than five pupils are in this group for the current view, so these findings are suppressed to protect pupil identity, in line with GDPR. The greyed charts show the whole school for context.",
    "ui.a11y_switch": "Accessibility features",
    "ui.a11y_glossary_heading": "Glossary of terms used in this report",
    "ui.a11y_glossary_intro": "Select a term to open its explanation in the guide.",
}
TRANSLATE_ORDER = [
    ("Page text", ["ui005","ui183","ui032","ui186","ui187","ui188","ui189","ui195","ui200","ui225","ui226","ui227","ui228","ui230","ui247","ui004","ui000","ui054","ui055","ui001","ui185"]),
    ("Chart headings, group names and footnotes", ["dl_combined","ed_combined","ws_combined","settings_dl","settings_dy","settings_ly","responses_by_gender_base_note","ethnicity_group_base_note"]),
    ("Discussion questions for schools", ["h2_generic_reflect","h2_generic_discussion"]),
    ("Sentences with placeholders (keep the {…} parts exactly)", ["ui.chart_sports_total_club","ui.chart_sports_total_community","ui.chart_sports_total_other","ui.doc_title","ui.fsm_context_title","ui.fsm_context_body","ui.fsm_context_value","ui.review_note","ui.meta_version_value"]),
    ("Technical record labels", ["ui.meta_survey_year","ui.meta_report_version","ui.meta_pipeline","ui.meta_suppression","ui.meta_generated","ui.meta_checksum","ui.meta_weighting","ui.meta_weighting_value"]),
    ("Data-protection messages", ["ui.gdpr_body_full","ui.gdpr_body_module"]),
    ("Accessibility switch (new)", ["ui.a11y_switch","ui.a11y_glossary_heading","ui.a11y_glossary_intro"]),
    ("Screen-reader names (not visible on the page)", ["ui.aria_cover","ui.aria_toc","ui.nav_aria"]),
]

# Sheet 4 — the rules, in plain English, with an example from the report.
# (area, rule, example, sheet reference)
RULES = [
    ("How sentences are built",
     "Every finding is written verb-first, in the style of Sport Wales and Welsh Government statistical reports: “Dywedodd 159 o’r 363 disgybl … eu bod yn …”. A sentence never starts with a figure.",
     "Dywedodd 159 o’r 363 disgybl yn yr ysgol gyfan a ymatebodd eu bod yn cymryd rhan mewn o leiaf un gamp mewn clwb ysgol.", "SYN-01"),
    ("How sentences are built",
     "The verb stands first without the affirmative particle: “Cymerodd disgyblion … ran”, not “Fe gymerodd …”. PLEASE CHECK: your own translation of these sentences used “fe gymerodd”. Both are grammatical; the report needs one register.",
     "Cymerodd 251 o’r 366 disgybl yn yr ysgol gyfan ran mewn chwaraeon clwb …", "SYN-01 (attested Sport Wales prose)"),
    ("How sentences are built",
     "“Took part” is written with the split verb: “Cymerodd … ran mewn …”, never “Cymerodd X rhan”.",
     "Cymerodd naw o’r 12 merch ym Mlwyddyn 5 ran mewn chwaraeon clwb o leiaf unwaith yr wythnos.", "SYN-02"),
    ("How sentences are built",
     "“The largest group said X” is written as a cleft with the answer first: “‘X’ oedd yr ateb a ddewiswyd amlaf (60, neu 16%)”.",
     "O’r 366 disgybl yn yr ysgol gyfan a ymatebodd, ‘4’ oedd yr ateb a ddewiswyd amlaf (60, neu 16%).", "PR-08"),
    ("How sentences are built",
     "A comparison uses “o gymharu â” (with the aspirate mutation) or “o gymharu ag” before a vowel.",
     "… dywedodd 24 o’r 174 (14%) nad ydynt yn aml, neu byth, yn ei chael hi’n hawdd ymuno, o gymharu â 27 o’r 186 (15%) o ferched.", "SYN-07"),
    ("How sentences are built",
     "A contrast between two groups uses “tra bo …”.",
     "Tennis oedd ar y brig ymhlith bechgyn (91 o ddewisiadau), tra bo marchogaeth ceffylau ar y brig ymhlith merched (83 o ddewisiadau).", "SYN-08, D12"),
    ("How sentences are built",
     "“Among” is always “ymhlith” (not “ymysg”); “of those who …” is “o blith y … a …”.",
     "Ymhlith bechgyn yn yr ysgol gyfan, dywedodd 24 o’r 174 (14%) …", "D10, SYN-10"),
    ("How sentences are built",
     "The English agentless passive (“Pupils were asked …”) is written with the impersonal verb form: “Gofynnwyd i ddisgyblion …”, “Dewiswyd ‘X’ gan 12 o ddisgyblion”.",
     "Pan ofynnwyd iddynt a yw gwersi AG a Gwersi Actif yn gwneud iddynt deimlo’n iach …  /  ‘Cael hwyl’ oedd yr opsiwn a ddewiswyd amlaf …", "SYN-05, D17"),
    ("How sentences are built",
     "“Highest … lowest” uses “ar ei uchaf … ac ar ei isaf”; the possessive agrees with the gender of the subject noun (nifer → ei uchaf; canran/cyfran → ei huchaf).",
     "Roedd cyfranogiad … ar ei uchaf ym Mlwyddyn 6 (28 o’r 29, neu 97%) ac ar ei isaf ym Mlwyddyn 10 (40 o’r 48, neu 83%).", "SYN-06"),
    ("Zero and one",
     "When nobody chose an answer, the sentence says what was NOT chosen with “Ni ddewisodd yr un o’r …”, rather than stacking two negatives.",
     "Ni ddewisodd yr un o’r 12 merch ym Mlwyddyn 5 ‘Nac ydw, dim yn aml’ na ‘Byth’ ynghylch ymuno â chwaraeon a gemau.", "PR-02"),
    ("Zero and one",
     "When only one pupil is described and the report does not know whether they are a boy or a girl, the sentence avoids “he/she” by using an impersonal form (“Nodwyd gan un disgybl …”) or agrees with the grammatical gender of the noun (“yr unig ddisgybl … ei ysgol”).",
     "Roedd yr unig fachgen ym Mlwyddyn 3 a ddywedodd yr hoffai gymryd rhan mewn mwy o fowls …  /  yr unig fachgen … y byddai’n well ganddo beidio â dweud a oedd ganddo anabledd …  /  yr unig ferch … pe bai ganddi yr hyn sydd ei angen", "PR-03, PR-14"),
    ("Numbers",
     "Survey results are always shown as figures (12, 366, 16%), never as words. Words are used only for small counts inside a few fixed phrases (see the next rule).",
     "Cymerodd 251 o’r 366 disgybl … ran …", "D02"),
    ("Numbers",
     "A figure followed by “o” takes the plural noun with soft mutation: “12 o ddisgyblion”, “221 o ddewisiadau”. But after a numeral WITH the article the noun is singular: “y 12 disgybl”, “o’r 366 disgybl”.",
     "gyda 221 o ddewisiadau  /  o’r 366 disgybl yn yr ysgol gyfan", "PL-09"),
    ("Numbers",
     "Counts of one to ten inside fixed phrases use the Welsh number words with the right gender and mutation, from a fixed table: un disgybl, dau ddisgybl, tri disgybl, pum disgybl, chwe disgybl; y ddwy gamp, y tair camp, y chwe champ, yr wyth camp.",
     "yn ôl chwech o’r chwe disgybl a ymatebodd  /  ran mewn dwy o gampau  /  (tri disgybl)  /  table caption: Y deg camp a ddewiswyd amlaf yn y golwg hwn", "Sheet 50"),
    ("Numbers",
     "“and” before a figure is “a” or “ac” depending on how the figure is READ ALOUD in Welsh, using the traditional (vigesimal) numbers: “ac 11” (ac un ar ddeg), “ac 8” (ac wyth), “ac 36” (ac un ar bymtheg ar hugain), but “a 3”, “a 12”. PLEASE CHECK THIS ONE CAREFULLY: if readers would say “tri deg chwech”, then “ac 36” is wrong and the rule should use the decimal reading.",
     "dywedodd 48 o’r 87 bachgen ac 36 o’r 91 merch a ymatebodd eu bod …", "CONJ-06"),
    ("Numbers",
     "Ordinals are the traditional forms: cyntaf (which FOLLOWS its noun: y gamp gyntaf), ail, trydydd/trydedd, pedwerydd/pedwaredd … “The second most common” is “Yr ail … mwyaf cyffredin”.",
     "Yr ail opsiwn mwyaf cyffredin oedd ‘Bod gyda ffrindiau’ …  /  Yr ail camp neu weithgaredd mwyaf cyffredin oedd pêl droed (PLEASE CHECK: should “camp” mutate after “ail” → “Yr ail gamp”? This appears 2,465 times in the test school’s report.)", "Sheet 09, ADJ-11"),
    ("Numbers",
     "A figure that ENDS in 2 (12, 22, 32 …) does not mutate the noun that follows: “22 disgybl”. PLEASE CHECK: in your own translation of the page you wrote “Yn seiliedig ar: 22 ddisgybl”, with the soft mutation — if that is right, the rule is wrong for every number ending in 2.",
     "Yn seiliedig ar: 22 disgybl  /  o’r 12 merch ym Mlwyddyn 5", "Sheet 08 / PL-09"),
    ("Numbers",
     "Percentages are written “16%” with no space, and “neu 16%” (“or 16%”) after the count in brackets.",
     "(60, neu 16%)", "D02"),
    ("Mutations",
     "After “o”, “i”, “am”, “ar”, “gan”, “dros”, “drwy”, “wrth”, “heb”: soft mutation on the next word (o ddisgyblion, o fechgyn, o ferched, i ddisgyblion, gan ddisgyblion).",
     "gan 86 o’r 92 disgybl a nododd anabledd …  /  o ferched", "Sheet 07"),
    ("Mutations",
     "After locative “yn” (in): nasal mutation and the form of yn changes — ym Mlwyddyn 8, yng Nghymru, ym Mhowys. No mutation before the article: yn yr ysgol, yn y clwb.",
     "merched ym Mlwyddyn 4  /  yn yr ysgol gyfan", "Sheet 07"),
    ("Mutations",
     "After the conjunction “a” (and): aspirate mutation (a chriced, a phêl droed, a thennis); “ac” before a vowel and before mae/roedd/sydd/felly, and “ac” causes no mutation.",
     "… o leiaf unwaith yr wythnos, a chymerodd 142 o’r 366 (39%) ran mewn chwaraeon clwb  /  ac yna Rhywle arall (81)", "CONJ-01…04, PR-13"),
    ("Mutations",
     "After “neu” (or): soft mutation on nouns and adjectives (Rhedeg neu Loncian; camp neu weithgaredd).",
     "y gamp neu weithgaredd a ddewiswyd amlaf", "CONJ-09"),
    ("Mutations",
     "“mewn” (in a …) causes no mutation and never takes the article: mewn clwb, mewn gwersi AG. With “the” it becomes “yn y / yn yr”.",
     "mewn clwb y tu allan i’r ysgol  /  yn y clwb", "Sheet 12"),
    ("Mutations",
     "A feminine singular noun mutates after the article (y gamp, y ferch, y ganran) and mutates a following adjective (y gamp fwyaf poblogaidd). Plurals do not (y merched, campau poblogaidd).",
     "y gamp a ddewiswyd amlaf  /  y cyfranogiad uchaf", "ART-06, ADJ-02"),
    ("Mutations",
     "After “un” a feminine noun mutates (un gamp); after “dau/dwy” everything mutates (dau ddisgybl, dwy gamp); after “tri” and “chwe” the aspirate (tri chlwb, chwe champ); after “pum”, “saith”, “wyth”, “naw”, “deg” no mutation.",
     "o leiaf un gamp  /  y ddwy gamp  /  y chwe champ", "Sheet 08"),
    ("Mutations",
     "The setting “somewhere else” is written as the survey’s label “rhywle arall”, unmutated, after a verb phrase (“ran mewn chwech o gampau rhywle arall”). PLEASE CHECK: your translation of the same sentence wrote “6 champ rywle arall” — mutating the noun after “chwe(ch)” AND mutating “rhywle” as an adverb. If both are right, two rules change.",
     "cymerodd disgyblion … ran mewn chwech o gampau rhywle arall", "Sheet 07 (chwe → aspirate; adverbial noun → soft)"),
    ("Mutations",
     "Unadapted sport names (BMX, Boccia, Parkour, Taekwondo …) never mutate. Other sport names do (pêl droed → bêl droed after “o”, “am”, “gan”).",
     "Dewisodd 81 o ddisgyblion bêl osgoi …", "PR-05"),
    ("Mutations",
     "Sport names are written in lower case inside sentences (pêl droed, nofio, rygbi) and in Title Case in tables, charts and answer labels.",
     "Y campau a ddewiswyd amlaf gan ddisgyblion yn yr ysgol gyfan oedd tennis (273), pêl droed (221) a rhedeg neu loncian (214).  /  chart label: Pêl Droed", "D21, PR-10"),
    ("Mutations",
     "The article is “yr” before a vowel or h, “’r” after a word ending in a vowel, otherwise “y”: yr ysgol, o’r disgyblion, y gamp.",
     "o’r 366 disgybl  /  yr ail  /  y lleoliad", "Sheet 10"),
    ("Relative clauses (“who …”)",
     "“Pupils who chose X” is “disgyblion a ddewisodd X”: the particle “a” with soft mutation on the verb, and the verb is always third person SINGULAR even when the subject is plural (“a ddewisodd”, never “a ddewisasant”).",
     "y disgyblion a ddewisodd saethyddiaeth  /  disgyblion … a ddywedodd eu bod …", "REL-01, REL-09"),
    ("Relative clauses (“who …”)",
     "Present tense “who are / who do” uses “sydd” or “sy’n” with no particle: “disgyblion sy’n dod o gefndir ethnig amrywiol”.",
     "gan 42 o’r 45 disgybl sy’n dod o gefndir ethnig amrywiol", "REL-02"),
    ("Relative clauses (“who …”)",
     "Negative relatives use “nad” / “na”: “disgyblion nad ydynt yn siarad Cymraeg”, “y rhai na ddewisodd …”.",
     "… nad ydynt yn aml, neu byth, yn ei chael hi’n hawdd ymuno", "REL-07"),
    ("Relative clauses (“who …”)",
     "“The sport they would like to do more of” is an object-of-preposition relative and carries an inflected preposition agreeing with the noun: “y gamp yr oedd y galw mwyaf amdani” (camp is feminine → amdani), “rhywbeth yr hoffent wneud mwy ohono”.",
     "fel rhywbeth yr hoffent wneud mwy ohono ond nad ydynt yn ei wneud ar hyn o bryd", "REL-06"),
    ("Relative clauses (“who …”)",
     "Welsh has no participles, so “pupils selecting Tennis” is always a full relative clause (“disgyblion a ddewisodd Tennis”).",
     "y disgyblion a ddewisodd athletau", "REL-10"),
    ("Agreement and gender",
     "Every answer label has a grammatical gender in our table so that it can head a sentence correctly. Verb-nouns and unadapted loan words are treated as masculine unless the dictionary says otherwise.",
     "‘Cael hwyl’ oedd yr opsiwn a ddewiswyd amlaf …", "PR-01"),
    ("Agreement and gender",
     "“camp neu weithgaredd” (sport or activity) agrees with the nearer noun (gweithgaredd, masculine).",
     "y gamp neu weithgaredd a ddewiswyd amlaf", "PR-06"),
    ("Agreement and gender",
     "“golwg” (view) is treated as masculine: “y golwg hwn”.",
     "y lleoliad mwyaf cyffredin yn y golwg hwn", "PR-07"),
    ("Agreement and gender",
     "“Very” follows the adjective (iach iawn, hyderus iawn); “quite” precedes it (eithaf iach). “dim ond” is used for “only”, never “jyst”.",
     "eu bod yn teimlo’n ‘iach iawn’ neu’n ‘eithaf iach’", "ADJ-12, ADJ-17"),
    ("Quoting the survey",
     "Answer options are quoted inside sentences in single curly quotes, exactly as the pupils saw them in the Welsh survey, with no mutation inside the quotes.",
     "dywedodd 313 o’r 366 a ymatebodd ‘Hyderus Iawn’ neu ‘Eithaf hyderus’", "D21 / sheet 23"),
    ("Quoting the survey",
     "A group defined by an answer is described by echoing the survey question’s verb: pupils who said “Oes” to the disability question are “disgyblion a nododd anabledd neu gyflwr tymor hir”; a group with no survey question (ethnically diverse background) is NAMED instead of answered.",
     "disgybl a nododd anabledd neu gyflwr tymor hir  /  disgyblion sy’n dod o gefndir ethnig amrywiol", "PR-11"),
    ("Punctuation and style",
     "Curly apostrophes (’) and curly quotes (‘ ’, “ ”) throughout; the ampersand (&) is never used; a list of three or more is “A, B a C” (or “ac C” before a vowel).",
     "tennis (273), pêl droed (221) a rhedeg neu loncian (214)", "CONJ-10, CONJ-11"),
    ("Punctuation and style",
     "The people in a sentence are always “disgyblion” (pupils); “bechgyn” and “merched” are used only when the view is filtered by gender, and the year group is added when the view is filtered by year (“merched ym Mlwyddyn 5”).",
     "Ymhlith merched yn yr ysgol gyfan …  /  Cymerodd naw o’r 12 merch ym Mlwyddyn 5 ran …", "Sheet 20"),
    ("Punctuation and style",
     "The place names of the school (local authority, regional partnership) are shown in their Welsh form from your document (Sir Benfro, Partneriaeth Chwaraeon Gorllewin Cymru).",
     "Awdurdod Lleol: Sir Benfro", "Sheet 53"),
]

GLOSSARY = [
    ("Report / Interactive Learning Report", "The web page each school receives. It has a filter panel on the right; changing a filter changes every chart AND every written sentence."),
    ("View", "One combination of filters — for example “Year 5 · Girls” or “Whole school · All pupils · Selected Football”. The report has 8,568 possible views for this school."),
    ("Generated sentence", "A Welsh sentence written by our software from a fact in the data (a count, a comparison, a ranking), using the rules on sheet 4. There are about 300,000 of them in this one school’s report, so they cannot be translated one by one."),
    ("Page text / static text", "Text that is the same in every view: headings, the guide, the introduction, notes. This WAS translated by you and is what sheets 1–3 are about."),
    ("Frame", "A sentence with placeholders that the software fills in — for example “Based on: {n} pupils”. The placeholders look like {n}, {school}, {value} and must be kept exactly."),
    ("Answer label / answer option", "The wording of an answer in the survey (“Llawer”, “Dim o gwbl”, “Pe bai mwy o chwaraeon rydw i’n eu hoffi”). The report quotes these inside sentences."),
    ("Base", "The number of pupils a chart or sentence is based on — “Based on: 366 pupils”."),
    ("Filter group / cohort", "A group of pupils chosen from a chart or the “Pupil group” list — for example pupils who chose Football, or pupils with a disability."),
    ("Suppressed / hidden", "Results for fewer than five pupils are not shown, to protect the pupils’ identity. The report shows “—” or a grey bar instead."),
    ("Mutation (treiglad)", "The change to the first letter of a Welsh word after certain words (o ddisgyblion, y gamp, ym Mlwyddyn 8). Our software applies these by rule; sheet 4 lists the rules."),
    ("Setting (lleoliad)", "Where sport happens: PE and lesson time, a school sports club, a club outside school, or somewhere else."),
    ("Key (ui034, ui.doc_title …)", "Our reference code for a piece of text. Please leave the keys as they are — we use them to put your Welsh in the right place."),
]
