# -*- coding: utf-8 -*-
"""Sheet 1 — Confirm corrections. Each row: key, where it appears, what we found
(plain English), what we need, kind ('confirm' = we already changed it, please
confirm; 'rewrite' = we need a new sentence from you)."""

CORRECTIONS = [
    ("ui034", "Guide page — the answer to “What is an interactive report?”",
     "The sentence used “Yn eich tro”, which means “in your turn”. The English means “in turn / as a result”. A reviewer suggested “Yn ei dro”. The report shows YOUR text unchanged.",
     "Tell us whether to keep “Yn eich tro”, use “Yn ei dro”, or use another connective (for example “O ganlyniad”).", "confirm"),
    ("ui057", "Guide page — the answer to “What do the different colours mean?”",
     "The English says dark grey *marks* hidden values (marks = shows). The Welsh had “marciau llwyd tywyll”, which reads as “dark-grey marks” (a noun). A reviewer suggested “mae barrau llwyd tywyll yn dynodi gwerthoedd cuddiedig”. The report shows YOUR text unchanged.",
     "Keep your clause, take the suggestion, or give new wording for “dark grey marks suppressed values”.", "confirm"),
    ("ui064", "Guide page — a question heading: “Why are some bars grey, blank or not clickable?”",
     "The question mixed two constructions after one “Pam” (“mae …” and “nid oes …”). A reviewer suggested “Pam mae rhai barrau’n llwyd neu’n wag, neu pam na ellir clicio arnynt?”. The report shows YOUR text unchanged.",
     "Keep your question, take the suggestion, or give your version.", "confirm"),
    ("ui086", "Guide page — the answer to “Why don’t some numbers add to the total number of pupil responses?”",
     "The phrase “mae cwestiynau dilynol … yn cael eu holi” makes the *questions* the thing being questioned. The English means the questions are *asked* of certain pupils. We have NOT changed this — it needs a rewrite by you.",
     "Please rewrite the sentence so that it says the follow-up questions were asked only of pupils who used that setting. Write the whole sentence in the yellow cell.", "rewrite"),
    ("ui087", "Guide page — a question heading: “Why do some numbers become hidden after applying filters?”",
     "“mae rhai rhifau yn cuddio” says the numbers hide themselves. The English means they *become hidden*. A reviewer suggested “mae rhai rhifau’n cael eu cuddio”. The report shows YOUR text unchanged.",
     "Keep your wording, take the suggestion, or give your version.", "confirm"),
    ("ui095", "“Which pupils in our school took part in 2026?” page — the opening paragraph",
     "“o gylch hwn yr arolwg” had the words in the wrong order. A reviewer suggested “o gylch yr arolwg hwn”. The report shows YOUR text unchanged.",
     "Keep your wording, take the suggestion, or give your version.", "confirm"),
    ("ui104", "Guide page — a bullet in the answer to “How do I use filters?”",
     "“Cliciwch … ac archwilio …” joins a command (Cliciwch) with a verb-noun (archwilio). A reviewer suggested two commands: “Cliciwch … ac archwiliwch …”. The report shows YOUR text unchanged.",
     "Keep your wording, take the suggestion, or use “Cliciwch … i archwilio …”.", "confirm"),
    ("ui143", "Disability and long-term condition section — the introductory paragraph",
     "Two things. (1) “i disgyblion” appears to be missing the soft mutation after “i” — a reviewer suggested “i ddisgyblion”. (2) The three groups of pupils (those who said yes, those who were not sure, those who preferred not to say) are not written as parallel clauses — the last one starts “neu roedd …” while the others are relative clauses. We have NOT changed (2).",
     "Decide (1), and rewrite the sentence so that the three groups are listed in the same grammatical form. Write the whole paragraph in the yellow cell.", "rewrite"),
    ("ui154", "Section heading: “How do PE and Active Lessons make our pupils feel?”",
     "The English joins the two with “and”; the Welsh had “neu” (“or”). A reviewer suggested “AG a Gwersi Actif”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
    ("ui157", "“What is most important to pupils” section — the introductory paragraph",
     "Two things. (1) The paragraph has no closing full stop — a reviewer suggested adding one. (2) The paragraph uses “pan roeddent”; we would like to know whether “pan oeddent” is the better form here.",
     "Decide (1), and tell us which form you prefer in (2): “pan roeddent” or “pan oeddent”. If you prefer “pan oeddent”, write the corrected sentence in the yellow cell.", "rewrite"),
    ("ui190", "“Thank you and next steps” page — first paragraph",
     "“bob disgybl a rannodd eu barn” mixed a singular (bob disgybl) with a plural possessive (eu barn). A reviewer suggested “yr holl ddisgyblion a rannodd eu barn”. The report shows YOUR text unchanged.",
     "Keep your wording, take the suggestion, or give your version.", "confirm"),
    ("ui197", "Appendix page — the introductory paragraph",
     "The plural of “rhestr” was written “Rhestri” / “restri”. A reviewer suggested “Rhestrau” / “restrau”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
    ("ui250", "Note under the chart of participation by gender and year group",
     "The English says “Other genders” (plural); the Welsh had the singular “rhywedd arall”. We have NOT changed this — it is a wording choice for you.",
     "Please give us the Welsh you would use for the bracketed sentence “(Other genders are not shown here because the sample sizes are small.)”. Write the whole bracketed sentence in the yellow cell.", "rewrite"),
    ("ui254", "Guide page — a bullet in the answer to “How do I use filters?”",
     "“Defnyddio panel …” is a verb-noun; the English is a direct instruction. A reviewer suggested “Defnyddiwch banel …”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
    ("ui255", "Guide page — the answer to “What do the grey bars and greyed-out sections mean?” (first paragraph)",
     "Two things. (1) “Mae hwn yn cynnwys …” pointed at the bar; the English “This” points at the situation, so a reviewer suggested “Mae hyn yn cynnwys …”. (2) Later in the paragraph the Welsh uses singular agreement (“i’w ddefnyddio fel hidlydd”) where the English refers to plural *response options*. We have NOT changed (2).",
     "Decide (1), and rewrite the second sentence so that it agrees with the plural “opsiynau ymateb”. Write the whole paragraph in the yellow cell.", "rewrite"),
    ("ui257", "Guide page — the answer to “What do the grey bars and greyed-out sections mean?” (second paragraph)",
     "The plural “barrau llwyd tywyll” was explained by a singular “gwerth na ellir ei ddangos”. A reviewer suggested the plural “gwerthoedd na ellir eu dangos”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
    ("community_club_freq", "Chart heading: “How often are our pupils active through sport in a Club Outside of School each week?”",
     "A club is a place, but the Welsh used the time expression “yn ystod” (“during”). A reviewer suggested “mewn clwb y tu allan i’r ysgol”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
    ("other_setting_freq", "Chart heading: “How often are our pupils active through sport Somewhere Else?”",
     "“gwneud chwaraeon Rhywle arall” had no linking word before “Rhywle arall”. A reviewer suggested “yn rhywle arall”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion. (Note: “Somewhere Else” is also the name of an answer option in the survey — “Rhywle arall” — so please keep that wording inside the phrase.)", "confirm"),
    ("sports_other_setting", "Chart heading: “Which sports do pupils say they do Somewhere Else?”",
     "Same as the row above: “eu gwneud Rhywle arall” had no linking word. A reviewer suggested “eu gwneud yn rhywle arall”. The report shows YOUR text unchanged.",
     "Keep your wording or take the suggestion.", "confirm"),
]
