# -*- coding: utf-8 -*-
"""Sheet 2 — Decide wording. Each row: key, where it appears, the question in
plain English, our suggested wording (may be empty), what we need."""

DECISIONS = [
    ("ui009", "Introduction — the opening paragraph",
     "The last clause (about how children want sport to look in the future) reads awkwardly to us and may not say what the English says: “how they want sport to look in the future”.",
     "", "Tell us whether the last clause is natural Welsh. If not, write the clause (or the whole sentence) as you would say it."),
    ("ui016", "Introduction — the paragraph beginning “Together, your responses …”",
     "“i ddeall beth sydd bwysicaf … yn well” puts “yn well” (better) a long way from the verb, so it can attach to the wrong idea.",
     "i ddeall yn well beth sydd bwysicaf i blant a phobl ifanc", "Choose: keep as it is, use the suggestion, or give your own wording."),
    ("ui027", "Contents page — the description under “Sport Specific Data”",
     "“y campau yr hoffent wneud mwy ohonynt” — should there be an object pronoun, i.e. “yr hoffent *eu* gwneud mwy ohonynt”? The same construction appears in three other places (rows ui171, sports_wanted and unmet_demand below); we will apply your answer to all of them.",
     "y campau yr hoffent eu gwneud mwy ohonynt", "Tell us the correct form of “the sports they would like to do more of”. We will use it everywhere."),
    ("ui084", "Guide page — the answer to “Why don’t some percentages add to 100%?”",
     "“pam nad yw canrannau efallai’n adio i 100%” — the position of “efallai” (perhaps) reads oddly to us.",
     "Mae dau reswm pam efallai nad yw’r canrannau’n adio i 100%.", "Choose: keep, use the suggestion, or give your own wording."),
    ("ui088", "Guide page — the answer to “Why do some numbers become hidden after applying filters?”",
     "The second sentence starts “Yn ei thro, mae gwybodaeth …”. Is “Yn ei thro” (agreeing with “gwybodaeth”) right here for “In turn”, or should it be the fixed phrase “Yn ei dro”, or a different connective such as “O ganlyniad”?",
     "O ganlyniad, mae gwybodaeth yn cael ei chuddio …", "Tell us which connective to use."),
    ("ui099", "“An Active Nation for Everyone” chapter — the opening paragraph",
     "“pa mor aml mae disgyblion yn actif” — elsewhere the report uses the more formal “pa mor aml y mae …” (with “y”). We would like one consistent form throughout the report.",
     "pa mor aml y mae disgyblion yn actif", "Tell us which form to use everywhere: “pa mor aml mae …” or “pa mor aml y mae …”. (Row ui166 is the same question.)"),
    ("ui109", "Section heading: “How are our pupils active through sport in School?”",
     "“yn yr Ysgol” has a capital Y in the middle of a heading. The English capitalises “School” as a label, but in Welsh we think it should be lower case.",
     "Sut mae ein disgyblion yn actif drwy chwaraeon yn yr ysgol?", "Choose: keep the capital, or use lower case. Your answer will also decide rows ui120, ui202 and ui224 (the same capitalisation question)."),
    ("ui110", "“In School” section — the introductory paragraph",
     "The paragraph says “ar draws 2 gyd-destun” with the figure 2. Should this be written as the word “dau gyd-destun” in running text? (The report always uses figures for survey results, but this is ordinary prose.)",
     "ar draws dau gyd-destun ysgol", "Tell us whether to use “2” or “dau” here. Row ui121 is the same question."),
    ("ui120", "Section heading: “How are our pupils active through sport Outside of School?”",
     "“y Tu allan i’r Ysgol” has capitals in the middle of the heading (see ui109).",
     "Sut mae ein disgyblion yn actif drwy chwaraeon y tu allan i’r ysgol?", "Same decision as ui109."),
    ("ui121", "“Outside of School” section — the first line of the introduction",
     "“ar draws 2 gyd-destun y tu allan i’r ysgol” — figure or word? (see ui110)",
     "ar draws dau gyd-destun y tu allan i’r ysgol", "Same decision as ui110."),
    ("ui144", "Section heading: “Where are our pupils from ethnically diverse backgrounds active?”",
     "“o gefndiroedd amrywiol yn ethnig” — we think “o gefndiroedd ethnig amrywiol” is the natural order. The same phrase is used in a chart heading (row settings_ed) and in the filter labels.",
     "Ble mae ein disgyblion o gefndiroedd ethnig amrywiol yn actif?", "Tell us the term to use for “ethnically diverse backgrounds”; we will use it everywhere."),
    ("ui163", "Enjoyment section — the paragraph introducing the table by year group",
     "“faint o ddisgyblion ym mhob grŵp blwyddyn ddywedodd eu bod …” — should there be a relative particle: “… a ddywedodd eu bod …”?",
     "Mae’r tabl yn dangos faint o ddisgyblion ym mhob grŵp blwyddyn a ddywedodd eu bod yn mwynhau chwaraeon ‘llawer’ ym mhob lleoliad.", "Choose: keep, use the suggestion, or give your own wording."),
    ("ui166", "Section heading: “How confident do our pupils feel?”",
     "“Pa mor hyderus mae ein disgyblion yn teimlo?” — with or without “y” (see ui099)?",
     "Pa mor hyderus y mae ein disgyblion yn teimlo?", "Same decision as ui099."),
    ("ui171", "“Sport Specific Data” chapter — the opening paragraph",
     "Contains “y chwaraeon yr hoffent wneud mwy ohonynt” — the same object-relative question as ui027.",
     "y chwaraeon yr hoffent eu gwneud mwy ohonynt", "Same decision as ui027."),
    ("ui202", "Side panel — the heading above the list of report sections",
     "“Cliciwch i Neidio i ran o’r adroddiad” has a capital N on “Neidio” mid-sentence (see ui109).",
     "Cliciwch i neidio i ran o’r adroddiad", "Same decision as ui109."),
    ("ui217", "Chart heading: “Do PE and Active Lessons make you feel: Healthy?”",
     "In the English the heading is a question stem plus an answer (“… make you feel: Healthy?”). The Welsh copies the colon: “… yn gwneud i chi deimlo: Yn iach?”, which is not a natural Welsh question. We would prefer one complete question per chart.",
     "A yw AG a Gwersi Actif yn gwneud i chi deimlo’n iach?", "Give us one complete Welsh question for this chart (or confirm the suggestion). Rows ui218–ui223 are the same pattern."),
    ("ui218", "Chart heading: “Do PE and Active Lessons make you feel: Confident?”",
     "Same pattern as ui217.", "A yw AG a Gwersi Actif yn gwneud i chi deimlo’n hyderus?", "One complete Welsh question."),
    ("ui219", "Chart heading: “Do PE and Active Lessons make you feel: Ready to learn?”",
     "Same pattern as ui217.", "A yw AG a Gwersi Actif yn gwneud i chi deimlo’n barod i ddysgu?", "One complete Welsh question."),
    ("ui220", "Chart heading: “How much do pupils enjoy sport: in PE Lessons?”",
     "Same pattern as ui217 — the colon interrupts the question before the place.", "Faint mae disgyblion yn mwynhau chwaraeon mewn gwersi AG?", "One complete Welsh question."),
    ("ui221", "Chart heading: “How much do pupils enjoy sport: in School Sports Clubs?”",
     "Same pattern as ui217.", "Faint mae disgyblion yn mwynhau chwaraeon mewn clybiau chwaraeon ysgol?", "One complete Welsh question. Please use the same term for “School Sports Clubs” as in the survey (“Clybiau Chwaraeon Ysgol”)."),
    ("ui222", "Chart heading: “How much do pupils enjoy sport: in Clubs Outside of School?”",
     "Same pattern as ui217.", "Faint mae disgyblion yn mwynhau chwaraeon mewn clybiau y tu allan i’r ysgol?", "One complete Welsh question."),
    ("ui223", "Chart heading: “How much do pupils enjoy sport: in Other Settings, like the park or garden?”",
     "Same pattern as ui217, plus a capital M on “Mewn” mid-sentence.", "Faint mae disgyblion yn mwynhau chwaraeon mewn lleoliadau eraill, fel y parc neu’r ardd?", "One complete Welsh question."),
    ("ui224", "The label above every chart explanation: “What is this chart showing?”",
     "“Beth mae’r Siart hon yn ei ddangos?” has a capital S mid-sentence (see ui109).", "Beth mae’r siart hon yn ei ddangos?", "Same decision as ui109."),
    ("ui249", "Welsh-speaking pupils section — the introductory paragraph",
     "“Mae disgyblion y dywedont eu bod …” uses a literary form (“y dywedont”). Elsewhere the report uses the past “a ddywedodd”. We would like one consistent register.",
     "Mae disgyblion a ddywedodd eu bod yn siarad Cymraeg yn dda iawn, eithaf tipyn neu ychydig yn cael eu dangos yma.", "Choose: keep, use the suggestion, or give your own wording."),
    ("ui256", "Guide page — the answer to “What do the numbers tell me?” (worked example)",
     "The example refers back to two sports as “y ddau”. Because “camp” is feminine, should this be “y ddwy gamp” (or another neutral phrase)?",
     "y ddwy gamp", "Tell us how to refer back to “the two sports”."),
    ("disability_condition", "Chart heading: “How many of our pupils have a disability or long-term condition?”",
     "This heading says “cyflwr tymor hir”; your page text elsewhere uses “cyflwr hirdymor”. The survey pupils answered used “cyflwr tymor hir”. We need ONE term for “long-term condition” everywhere (headings, filter labels and thousands of generated sentences).",
     "cyflwr hirdymor", "Tell us the one term to use everywhere: “cyflwr tymor hir” or “cyflwr hirdymor”."),
    ("settings_ed", "Chart heading: “Where are our pupils from ethnically diverse backgrounds active through sport?”",
     "Same term question as ui144 (“cefndiroedd amrywiol yn ethnig” vs “cefndiroedd ethnig amrywiol”).", "Ble mae ein disgyblion o gefndiroedd ethnig amrywiol yn actif drwy chwaraeon?", "Same decision as ui144."),
    ("sports_wanted", "Chart heading: “Which sports would our pupils like to do more of?”",
     "Same object-relative question as ui027: “hoffai ein disgyblion wneud mwy ohonynt” or “… eu gwneud mwy ohonynt”?", "Pa chwaraeon yr hoffai ein disgyblion eu gwneud mwy ohonynt?", "Same decision as ui027."),
    ("unmet_demand", "Chart heading: “Which sports would our pupils like to do more of but are not currently doing?”",
     "Same object-relative question as ui027.", "Pa chwaraeon yr hoffai ein disgyblion eu gwneud mwy ohonynt, ond nad ydynt yn eu gwneud ar hyn o bryd?", "Same decision as ui027."),
    ("ui.note_other_sports", "Note under the sport charts explaining “Other sports”",
     "“unrhyw gampau” — “unrhyw” normally takes a singular noun (“unrhyw gamp”). Which is right here?", "unrhyw gamp", "Tell us: “unrhyw gampau” or “unrhyw gamp”."),
    ("ui.stack_caption_sex", "Caption of the data table under the participation-by-gender chart",
     "The caption says “yn ôl grŵp blwyddyn a rhywedd”. Your page text uses “rhywedd” for gender throughout, so we have aligned it; the survey itself used “Rhywedd” too. Please confirm “rhywedd” is the term for “gender” everywhere in the report.",
     "rhywedd", "Confirm “rhywedd”."),
]

# Block B — answer-option wording: the questions that arise from the differences
# between the translator's document and the wording of the survey itself.
ANSWER_WORDING = [
    ("AW-1", "Answer options quoted in the report",
     "The report quotes pupils’ answer options inside sentences, thousands of times — for example “dywedodd 92 o’r 366 ‘Dim Llawer’ neu ‘Dim o gwbl’”. The Welsh answer options in the report are copied EXACTLY from the Welsh survey the pupils filled in (for example “Dim Llawer”, “1 waith yr wythnos”, “Yn sefyll”, “Dydw i ddim yn gwybod”, “Pe bai mwy o chwaraeon rydw i’n eu hoffi”). Your document gives different wording for about 40 of them (for example “Ddim llawer”, “Unwaith yr wythnos”, “Sefyll”, “Ddim yn gwybod”, “Roedd mwy o chwaraeon rydw i’n eu hoffi”).",
     "Our recommendation: keep the survey wording, because it is what the pupils actually saw and chose.",
     "Tell us which to use in the report: (a) the survey’s wording, exactly as pupils saw it, or (b) the wording in your document. If (b), please confirm you are happy for the report to quote answers in words the pupils did not see."),
    ("AW-2", "The three “PE and Active Lessons” charts (Healthy / Confident / Ready to learn)",
     "The survey used the same four answers for all three questions: “Llawer / Eithaf / Dim llawer / Dim o gwbl”. Your document instead gives full phrases that differ by question (“Yn iach iawn”, “Yn hyderus iawn”, “Yn barod iawn i ddysgu” …). Our system can hold a different set of answer labels for each of the three questions, but only if you give us all twelve.",
     "", "If you want question-specific answers, fill in the twelve labels in the yellow cell (Healthy: very / quite / not very / not at all; Confident: …; Ready to learn: …). If you prefer the survey’s four shared answers, say “keep survey wording”."),
    ("AW-3", "The filter group “Ethnically diverse background: Yes / No”",
     "This group is not a survey question — it is built from the ethnicity question — so there is no “Oes / Nac oes” for pupils to have answered. The report currently names the group instead: “Cefndir ethnig amrywiol” and “Heb fod o gefndir ethnig amrywiol”. Your document gives “Oes / Nac oes”.",
     "Our recommendation: keep the named form, because the pupils never answered yes or no to this.",
     "Tell us: keep the named form, or use “Oes / Nac oes”."),
    ("AW-4", "One term for each concept",
     "Some concepts appear in several places (a chart heading, a filter label, a table caption and inside generated sentences) and currently use two forms. We need ONE form for each: “cyflwr tymor hir” or “cyflwr hirdymor”; “Dydw i ddim yn siŵr” or “Ddim yn siŵr”; “Mae’n well gen i beidio â dweud” or “Mae’n well gennyf beidio â dweud”; “Dim Llawer” or “Ddim llawer”; “Yn sefyll / Yn eistedd” or “Sefyll / Eistedd”; “camp / campau” or “chwaraeon” for a sport / sports (your note says “Chwaraeon eraill”, the chart label and every generated sentence say “camp”); “y golwg hwn” or “y wedd hon” for “this view” (your caption says “yn y wedd hon”; the report says “yn y golwg hwn”); “{n} ymateb disgybl wedi’u cynnwys” or “{n} ymateb gan ddisgyblion wedi’u cynnwys” for the banner count (your version uses “gan ddisgyblion”).",
     "", "For each pair, write the form to use everywhere in the yellow cell (one per line)."),
    ("AW-5", "Yes / No answers: the pupil’s voice or the report’s voice?",
     "Where a chart or filter shows a pupil’s yes/no answer, the report currently echoes the survey’s own answer word in the pupil’s voice, exactly as it appeared on screen: “Ydw / Nac ydw” (“Do you usually speak Welsh when you play sport?”), “Oes / Nac oes” (“Do you have a disability …?”). Your document writes these in the third person, as a report about the pupil: “Ydy / Nac ydy”. Both are correct Welsh; they are different points of view.",
     "Our recommendation: the survey’s form, so the report shows what the pupil ticked.",
     "Tell us which voice to use for every yes/no answer in the report (one decision covers all of them)."),
]
