# -*- coding: utf-8 -*-
"""Hand-written classifications for the fidelity audit (B frames, D generated
sentences, E client-rendered rows). Each entry: (what the translator wrote,
what the report has, why they differ — the mechanism, verdict, action)."""

V_OVERSIGHT = "Oversight — apply the translator's wording (exception to the rule / no rule involved)"
V_RULE = "Rule question — the framework rule produced this; the translator must confirm or correct the RULE"
V_DECISION = "Decision needed — depends on a label/term decision on the query sheet or handover sheet 2"
V_ENGINE = "Engine sentence — not a translation slot; the divergence is a pattern/rule question for the translator"
V_OWNER = "Owner — the English is locked / the owner has to decide first"
V_OK = "Already the translator's wording (applied in V4.11)"

# B — sheet-43 frames the translator's document also covered (18 distinct frames)
FRAMES = [
    ("ui.th_responses", "1 ymateb gan ddisgybl wedi’i gynnwys / 25 ymateb gan ddisgyblion wedi’u cynnwys", "Column heading “Ymatebion disgyblion”; the banner count is the frame ui.banner_showing “{n:count ymateb disgybl} wedi’u cynnwys”",
     "The translator translated the banner line with a number in it (“25 pupil responses included”). The report builds that line from a count-noun table (sheet 50: “ymateb disgybl”, plural after a figure) so that 1 / 2 / 25 are all right automatically. The translator's phrase uses “gan ddisgybl / gan ddisgyblion” (“from a pupil / from pupils”) where the table uses the compound “ymateb disgybl”.",
     V_RULE, "Put to the translator: is “{n} ymateb gan ddisgyblion wedi’u cynnwys” preferred to “{n} ymateb disgybl wedi’u cynnwys”? If so, the sheet-50 table for this noun changes (one edit, every count follows)."),
    ("ui.ghost_title", "Ysgol Gyfan – Blynyddoedd 3 – 11", "“Yr ysgol gyfan: {n} o’r {base} ({pct}%)”",
     "Not the same string: the translator translated the filter option name; the frame is the tooltip on the whole-school outline bar. The filter option name itself is on the query sheet (Ysgol Gyfan vs Yr ysgol gyfan).", V_DECISION, "Query sheet row 1."),
    ("ui.chip_none", "Dim un – dewiswch werth siart wedi’i amlygu i ychwanegu un", "Dim — dewiswch werth siart wedi’i amlygu i ychwanegu un",
     "Only “Dim un” vs “Dim” and the dash. The frame was not overwritten because the V4.10 ingest treated sheet-43 frames as framework-owned (only new frames took the translator's text).", V_OVERSIGHT, "Apply the translator's wording to the frame (V4.14)."),
    ("ui.base_line", "Yn seiliedig ar: 22 ddisgybl", "Yn seiliedig ar: {n:count disgybl}[ · caniateir mwy nag un ateb]",
     "The translator wrote “22 ddisgybl” — a soft mutation after 22 (dau ddeg dau). The report's count table (sheet 50 / rule PL-09) writes “22 disgybl” with no mutation, following the decimal reading in which only the numeral’s last word governs mutation and “dau” inside “dau ddeg dau” does not. This is a genuine rule question about mutation after decimal numerals ending in 2.", V_RULE, "Handover sheet 4, rules 12–13: ask explicitly whether a figure ending in 2 (12, 22, 32 …) mutates the following noun."),
    ("ui.click_note", "Cliciwch ar far i hidlo’r adroddiad yn ôl y disgyblion hyn", "Cliciwch ar far i hidlo’r adroddiad yn ôl y disgyblion hyn.",
     "Identical apart from the final full stop.", V_OK, "None."),
    ("ui.table_summary", "Gweld Tabl Data", "Gweld y tabl data",
     "Casing and the article: the translator gave the label in title case without the article. The frame kept the workbook's earlier value because frames were framework-owned in the V4.10 ingest.", V_OVERSIGHT, "Apply the translator's wording (V4.14); it is a button label, no slot."),
    ("ui.th_answer", "Ateb", "Ateb", "Same.", V_OK, "None."),
    ("ui.stack_th_sport", "Camp", "Camp", "Same.", V_OK, "None."),
    ("ui.stack_th_total", "Cyfanswm y Disgyblion", "Cyfanswm disgyblion", "Article and casing.", V_OVERSIGHT, "Apply the translator's wording (V4.14)."),
    ("ui.stack_table_caption", "Y 10 camp a ddewiswyd amlaf yn y wedd hon", "{k:count camp, definite, initial} a ddewiswyd amlaf yn y golwg hwn — {desc}",
     "Two things. (1) “yn y wedd hon” (translator) vs “yn y golwg hwn” (workbook ruling PR-07: golwg, masculine) — a terminology ruling the translator has now implicitly answered with a different noun. (2) The count is a slot realised by the sheet-50 table (“Y deg camp”, “Y naw camp”…) because the number changes with the data; the translator wrote “Y 10 camp” with the figure.", V_RULE, "Handover sheet 2 should carry the “gwedd / golwg” term question (add to AW-4); the figure-vs-word choice for counts 1–10 inside fixed phrases is sheet 4 rule 13."),
    ("ui.stack_caption_year", "… fesul grŵp blwyddyn", "… yn ôl grŵp blwyddyn", "“fesul” vs “yn ôl” for “by”.", V_OVERSIGHT, "Apply the translator's wording (V4.14); also align ui.stack_caption_sex (“… fesul grŵp blwyddyn a rhywedd”)."),
    ("ui.th_year_group", "Grŵp Blwyddyn", "Grŵp blwyddyn", "Casing only.", V_OVERSIGHT, "Apply the translator's casing (V4.14)."),
    ("ui.th_base", "Sylfaen", "Sail", "Different word for “Base”. The workbook's “Sail” came from the framework glossary; the translator uses “Sylfaen” here and in the guide's FAQ (“gall y rhif ‘sylfaen’ amrywio”, ui074), so the report currently uses two words for one term.", V_OVERSIGHT, "Apply “Sylfaen” to the frame (V4.14) so the table heading matches the translator's FAQ."),
    ("ui.note_other_sports", "Mae “Chwaraeon eraill” yn cyfeirio at unrhyw chwaraeon a ddewiswyd gan ddisgyblion …", "Mae “Campau eraill” yn cyfeirio at unrhyw gampau a ddewisodd disgyblion …",
     "The note quotes the chart label for the composite option “Other sports”, which is the sheet-23 answer label “Campau eraill”. The translator's note says “Chwaraeon eraill”. Changing the note alone would make it quote a label that does not appear on the chart; the label and the note have to change together (camp vs chwaraeon is a terminology choice that runs through the whole report: “camp” is used for a single sport throughout the engine's sentences).", V_DECISION, "Add “camp / chwaraeon for ‘sport(s)’” to AW-4; apply note + label together once decided."),
    ("ui.ranking_note", "Dangosir y prif 11 ateb o blith 60 ateb – mae’r tabl data yn rhestru pob un ohonynt", "Yn dangos y {k:count ateb} blaenaf o {n} — mae’r tabl data yn rhestru pob un",
     "Slot-bearing note; the translator's wording differs in the verb form (“Dangosir” impersonal vs “Yn dangos”), the adjective (“prif” before the noun vs “blaenaf” after) and “o blith”. The count slot stays.", V_OVERSIGHT, "Rebuild the frame on the translator's wording with the slots in place: “Dangosir y prif {k} ateb o blith {n} ateb – mae’r tabl data yn rhestru pob un ohonynt” (V4.14). Note “y prif {k} ateb” takes a figure, not the count-word table — consistent with the translator's own usage."),
    ("ui.f14_most", "Y chwaraeon y mae’r lefel uchaf o gymryd rhan ynddynt", "Y campau y cymerwyd rhan ynddynt fwyaf", "Different wording for the summary-table heading; also camp vs chwaraeon.", V_DECISION, "Apply the translator's heading once the camp/chwaraeon term is decided (AW-4)."),
    ("ui.f14_unmet", "Y galw mwyaf heb ei fodloni", "Y galw mwyaf heb ei ddiwallu", "“bodloni” vs “diwallu” for “unmet”. The engine's generated sentences also use “heb ei fodloni” (e.g. “Pêl osgoi oedd â’r galw mwyaf heb ei fodloni”), so the frame is the odd one out.", V_OVERSIGHT, "Apply the translator's wording (V4.14)."),
    ("ui.of", "Anabledd neu gyflwr hirdymor – mewn clwb y tu allan i’r ysgol", "{n} o’r {b}", "Mis-match in the V4.10 ingest: the translator's row is a chip name (see the query sheet / prefixes), not the “{n} of {b}” frame.", V_DECISION, "Chip prefix decision on the query sheet."),
]

# E — client-rendered rows (52 in the register); grouped
CLIENT = [
    ("All Pupils → Pob Disgybl", "Filter option “All pupils” = “Pob disgybl” (sheet 28)", "Casing only (Disgybl / disgybl).", V_OVERSIGHT, "Take the translator's casing for the option label; sentences keep lower case (D21 applies to sport names, and “pob disgybl” inside a sentence is lower case)."),
    ("Interactive Report → Adroddiad Rhyngweithiol", "Cover line ui005 and browser title ui.doc_title — both still pending", "The report's English is “Interactive Learning Report”, which the translator did not translate; “Adroddiad Rhyngweithiol” is a different string. Owner item E-6.", V_OWNER, "Owner to confirm the title; then translator supplies “Adroddiad Dysgu Rhyngweithiol” or approves the shorter form."),
    ("Primary Phase – Years 3 – 6 / Secondary Phase – Years 7 - 11 → Cyfnod Cynradd – Blynyddoedd 3 – 6 / Cyfnod Uwchradd – Blynyddoedd 7 – 11", "Scope options (filterOptions.scope labelCy)", "Check: the scope option labels come from the workbook (sheet 28 / D50 SCOPE_CY “Y cyfnod cynradd”). The translator's form drops the article and uses title case.", V_OVERSIGHT, "Apply the translator's option labels (V4.14) — option labels only; the sentence forms (“yn y cyfnod cynradd”) are audience forms and stay."),
    ("Speaks Welsh (very well, a fair amount, or a little): Yes → Yn siarad Cymraeg (yn dda iawn, cryn dipyn, neu ychydig): Ydy", "Cohort chip ws_yes (code prefix “Yn siarad Cymraeg (yn dda iawn, cryn dipyn neu ychydig): {x}”, answer by PR-11/D54)", "Prefix matches the translator's apart from the Oxford comma; the answer “Ydy” vs the report's D54 echo of the question verb.", V_DECISION, "Query sheet (prefix) + AW-3 style question for the derived group's answer."),
    ("Back / Next → Yn ôl / Nesaf", "Frames ui.nav_back “← Yn ôl”, ui.nav_next “Nesaf →”", "Applied in V4.11 (arrows are punctuation).", V_OK, "None."),
    ("Based on: 1 pupil → Yn seiliedig ar: 1 disgybl", "Frame ui.base_line → “Yn seiliedig ar: un disgybl” (sheet 50 count table writes 1–10 as words)", "The translator writes the figure “1”; the framework writes “un” for 1–10 inside fixed phrases (D02 exception for count-NPs).", V_RULE, "Sheet 4 rule 13: figure or word for 1–10 in fixed phrases — the translator's own practice here says figure."),
    ("Estimated times active through club sport each week: No club sport reported: 1 / 9+", "Chips cb_*", "The translator's row mixes two chips; see the query sheet rows 6–8.", V_DECISION, "Query sheet."),
    ("Disability or long term condition – sport in PE or lesson time (and 8 similar rows) → Anabledd neu gyflwr hirdymor – chwaraeon mewn AG neu amser gwersi …", "Chips gy/gl/gd/ge/gw: code prefixes “Anabledd neu gyflwr tymor hir · chwaraeon {x}” with the setting label from sheet 23", "Three differences, all in the code-written prefix: hirdymor vs tymor hir (AW-4 term), the separator (– vs ·), and the setting phrase (“mewn AG neu amser gwersi” vs the survey's “Yn ystod Addysg Gorfforol neu Amser Gwersi”). Nothing here is a rule; the prefixes were written in code (D50).", V_OVERSIGHT, "Move the chip prefixes into the workbook (new sheet) and take the translator's; the setting phrase inside them follows the label decision (query sheet row 5)."),
    ("Takes part: With Communication Aids / Prefer not to say → Yn cymryd rhan: Gyda Chymhorthion Cyfathrebu / Mae’n well gennyf beidio â dweud", "Chips tp_*", "Prefix (code, D50) + answer (survey: “Gyda chymhorthion cyfathrebu”, “Mae’n well gen i beidio â dweud”).", V_DECISION, "Query sheet (prefix + answer)."),
    ("Ethnically diverse background – sport … / Speaks Welsh – sport … (6 rows)", "Chips ge/gw", "As the disability rows: code prefix + setting label.", V_OVERSIGHT, "As above."),
    ("Speaks Welsh Playing Sport: Yes / No → Yn siarad Cymraeg wrth Wneud Chwaraeon: Ydy / Nac ydy", "Chip wl_* (code prefix “Y Gymraeg: {x}”; answer by D54 from the survey question “Wyt ti’n siarad Cymraeg fel arfer pan fyddi di’n gwneud chwaraeon? Ydw / Nac ydw”)", "The prefix is ours (D50) — take the translator's. The answer: the survey's is “Ydw / Nac ydw” (first person, as the pupil answered); the translator wrote “Ydy / Nac ydy” (third person, as a report about the pupil). D54 echoes the survey verb. A real register question.", V_RULE, "Add to the query sheet as an AW question: first-person survey answer or third-person report form for yes/no echoes (affects every yes/no chip and the D54 rule)."),
    ("Feels Healthy / Confident / Ready to Learn – Very / Quite / Not Very / Not at all (12 rows) → Yn Teimlo’n Iach – Iach iawn …", "Chips (family not selectable in the report today — no code prefix exists; the report's chips for these questions are the pe_feel labels)", "The translator wrote question-specific chips. The report's shared scale is the survey's (AW-2).", V_DECISION, "AW-2."),
    ("Values: Being with my friends / Winning / Liking my coach or teacher / Feeling Safe / Access to good equipment and facilities / Other (6 rows) → Gwerthoedd: …", "Chips im_* (code prefix “Yn gwerthfawrogi: {x}”; answers from the survey)", "Prefix is ours (D50); answers are the survey's and identical to the translator's (Bod gyda fy ffrindiau, Ennill, …).", V_OVERSIGHT, "Take the translator's prefix “Gwerthoedd:” (query sheet, prefix decision)."),
    ("Confidence trying sports in a new place: Very / Quite / Not Very / Not at all → Hyder i roi cynnig ar gamp mewn lle newydd: Hyderus iawn …", "Chips cn_*: code prefix “Hyder i roi cynnig ar chwaraeon mewn lle newydd:” + answers Hyderus Iawn / Eithaf Hyderus / Ddim yn hyderus iawn / Dim o gwbl", "Prefix: ours (D50) says “chwaraeon”, the translator “gamp” — take the translator's. Answers: the survey has “Hyderus Iawn / Eithaf Hyderus / Ddim yn hyderus iawn / Ddim yn hyderus o gwbl”; the report's fourth answer is “Dim o gwbl”, which is NOT the survey's option — sheet 23 maps the English “Not at all” to one generic label for every question. A genuine defect in the label table (the same generic-mapping weakness as the PE/Active Lessons scale).", V_OVERSIGHT, "Fix sheet 23: key the confidence questions' labels by question so “Not at all” → “Ddim yn hyderus o gwbl” (survey) for the four confidence questions; then AW-1 decides survey vs document as for every answer."),
    ("Selected: [insert sport] / Wants more: [insert Sport] / Has unmet demand for: [insert sport] → Dewiswyd: [ychwanegwch gamp] / Eisiau rhagor o: [ychwanegwch gamp] / Galw heb ei fodloni am: [ychwanegwch gamp]", "Chips sp/wd/f14 (code prefixes “Dewiswyd {x}”, “Eisiau mwy o {x}”; the sport name mutates after “o” by rule)", "Prefixes are ours (D50): the translator adds a colon and prefers “rhagor” to “mwy”. With a colon the sport name would follow as a citation (no mutation); without it the sport mutates after “o” (“Eisiau mwy o bêl droed”).", V_RULE, "Take the translator's prefixes; ask whether the sport name after “Eisiau rhagor o:” should mutate (colon = citation form, no mutation) — sheet 4 rule on quoted labels."),
]

# D — the translator's versions of 19 engine-generated sentences vs the engine's
GENERATED = [
    (1, "O’r 366 disgybl ar draws yr ysgol gyfan a atebodd, dywedodd y grŵp mwyaf (60, neu 16%) ‘4’.", "O’r 366 disgybl yn yr ysgol gyfan a ymatebodd, ‘4’ oedd yr ateb a ddewiswyd amlaf (60, neu 16%).",
     "(a) “ar draws yr ysgol gyfan” vs “yn yr ysgol gyfan” — the engine's audience form for the whole school (sheet 21). (b) “a atebodd” vs “a ymatebodd” (answered / responded) — the engine's predicate (sheet 19). (c) “dywedodd y grŵp mwyaf … ‘4’” — a literal “the largest group said” — vs the engine's cleft “‘4’ oedd yr ateb a ddewiswyd amlaf”, which is ruling PR-08 (Q14: ‘the largest group’ has no attested genre equivalent, so the engine avoids “y grŵp mwyaf”). The translator has just used it — which answers Q14.",
     V_ENGINE, "Three rule questions for the translator: the whole-school phrase (ar draws / yn), the verb (ateb / ymateb), and whether “dywedodd y grŵp mwyaf … ‘X’” is acceptable Welsh (if yes, PR-08 is withdrawn and 20,000+ sentences change form)."),
    (2, "… cymerodd disgyblion ar draws yr ysgol ran mewn 12 camp yn ystod y flwyddyn academaidd.", "… cymerodd disgyblion yn yr ysgol gyfan ran mewn 12 o gampau yn ystod y flwyddyn academaidd.",
     "“12 camp” (singular noun after a figure) vs “12 o gampau” (partitive). Both are grammatical; the framework chose the partitive for figures (PL-09 note, D02). The translator's instinct is the numeral+singular.", V_ENGINE, "Sheet 4 rule 12 — ask which form the report should use after figures; one ruling changes every count phrase."),
    (3, "… oedd Tennis (273), Pêl-droed (221) a Rhedeg neu loncian (214).", "… oedd tennis (273), pêl droed (221) a rhedeg neu loncian (214).",
     "Casing and hyphen: the translator keeps sport names in title case inside the sentence and writes “Pêl-droed”; the engine lower-cases sport names in prose (D21/PR-10) and uses the survey's unhyphenated “Pêl Droed” label form. Two rulings the translator has now taken a view on.", V_ENGINE, "Sheet 4 rule 25 (case) — and a spelling question: “pêl droed” (survey) or “pêl-droed” (translator)."),
    (4, "… fe gymerodd disgyblion … ran mewn 5 camp mewn AG neu amser gwersi …", "… cymerodd disgyblion … ran mewn pump o gampau yn ystod Addysg Gorfforol neu Amser Gwersi …",
     "(a) “fe gymerodd” (affirmative particle fe + mutation) vs bare “cymerodd” — register choice; the attested Sport Wales prose the framework copied uses the bare verb (SYN-01). (b) “5 camp” vs “pump o gampau” — figure vs word for 1–10 (D02) and singular vs partitive (as row 2). (c) “mewn AG neu amser gwersi” vs the survey's setting label “Yn ystod Addysg Gorfforol neu Amser Gwersi” — the engine quotes the survey setting label; the translator abbreviates.", V_ENGINE, "Sheet 4: rules 1 (fe), 11/13 (figures), and the setting-label question on the query sheet row 5."),
    (5, "… fe gymerodd disgyblion ar draws yr ysgol ran mewn un gamp mewn clwb ysgol …", "… cymerodd disgyblion yn yr ysgol gyfan ran mewn un gamp mewn clwb ysgol …", "Same as row 4 (a); otherwise identical — note both write “un gamp”.", V_ENGINE, "As row 4."),
    (6, "… ran mewn 6 champ rywle arall …", "… ran mewn chwech o gampau rhywle arall …",
     "“6 champ” — the translator applies the aspirate mutation after chwe(ch) to the noun and soft-mutates “rhywle” adverbially; the engine writes the word “chwech o gampau” (partitive, no mutation) and “rhywle arall” unmutated (the survey label). Both mutations the translator applied are rules the framework knows (chwe → aspirate; adverbial noun → soft) but does not fire in these positions.", V_ENGINE, "Sheet 4 rules 13 and 22 — plus a new question: does “rhywle arall” mutate adverbially after a verb phrase (“rywle arall”)?"),
    (7, "… ‘Dim adroddiad am chwaraeon clwb' ddywedodd y grŵp mwyaf (86, neu 23%).", "… ‘Dim chwaraeon clwb wedi’u nodi’ oedd yr ateb a ddewiswyd amlaf (86, neu 23%).",
     "As row 1 (cleft vs “the largest group said”), plus the label: the report's “Dim chwaraeon clwb wedi’u nodi” is our label for a derived option (“No club sport reported” is not a survey answer); the translator's is “Dim adroddiad am chwaraeon clwb”.", V_DECISION, "Query sheet row 8 for the label; row 1's PR-08 question for the sentence pattern."),
    (8, "… fe gymerodd disgyblion ag anabledd a/neu anhawster dysgu ar draws yr ysgol gyfan ran mewn 13 camp …", "… cymerodd disgyblion a nododd anabledd a/neu anhawster dysgu ymhlith disgyblion yn yr ysgol gyfan ran mewn 13 o gampau …",
     "The group description: translator “disgyblion ag anabledd …” (pupils with a disability — a noun phrase with ‘â/ag’) vs engine “disgyblion a nododd anabledd …” (pupils who reported a disability — a relative clause echoing the survey verb, D54/sheet 22). The engine's form is more cautious (it says what pupils reported, not what they have); the English says “with”. A wording policy question, not grammar.", V_ENGINE, "Put to the translator and the owner together: “â/ag anabledd” (with) or “a nododd anabledd” (who reported) — the English is “with”, the engine's Welsh is “who reported”; ~10,000 sentences."),
    (9, "… y gofynnwyd iddynt a oeddent yn siarad Cymraeg wrth wneud chwaraeon, dywedodd 17 …", "… y gofynnwyd iddynt a ydynt yn siarad Cymraeg wrth gymryd rhan mewn chwaraeon, atebodd 17 …",
     "Tense of the embedded question (“a oeddent” past vs “a ydynt” present), “wrth wneud chwaraeon” vs “wrth gymryd rhan mewn chwaraeon” (the survey's own question says “pan fyddi di’n gwneud chwaraeon”), and “dywedodd” vs “atebodd”.", V_ENGINE, "Sheet 5: add as a direct comparison; the survey's phrasing (“gwneud chwaraeon”) supports the translator on the second point."),
    (10, "Yr opsiwn mwyaf cyffredin nesaf a ddewiswyd oedd ‘Bod gyda ffrindiau’, gyda 225 disgybl ar draws yr ysgol gyfan yn dewis yr opsiwn hwn.", "Yr ail opsiwn mwyaf cyffredin oedd ‘Bod gyda ffrindiau’, gyda 225 o ddisgyblion yn dewis yr opsiwn hwn, ymhlith disgyblion yn yr ysgol gyfan.",
     "“The next most common” — translator “mwyaf cyffredin nesaf” (stacked, with ‘nesaf’ last) vs the engine's ordinal “Yr ail … mwyaf cyffredin” (ADJ-11: comparative/superlative must come last, so ‘next’ becomes ‘second’). Also “225 disgybl” vs “225 o ddisgyblion” (row 2) and the position of the audience phrase.", V_ENGINE, "Sheet 4 rule 15 (ADJ-11) — the translator's form is exactly what ADJ-11 forbids; ask which is right."),
    (11, "‘Cael hwyl’ oedd yr opsiwn mwyaf cyffredin a ddewiswyd gan fechgyn ar draws yr ysgol gyfan (141 disgybl).", "‘Cael hwyl’ oedd yr opsiwn a ddewiswyd amlaf gan fechgyn yn yr ysgol gyfan (141 disgybl).",
     "“yr opsiwn mwyaf cyffredin a ddewiswyd” vs “yr opsiwn a ddewiswyd amlaf” — two ways of saying ‘most common’; the engine's is the PR-08 cleft form used everywhere.", V_ENGINE, "Same question as row 1 (c)."),
    (12, "(girls — as row 11)", "(as row 11)", "As row 11.", V_ENGINE, "As row 11."),
    (13, "Nesaf roedd ‘Roeddwn i’n teimlo’n fwy hyderus’, gyda 117 o ddisgyblion ar draws yr ysgol gyfan yn dewis yr ateb hwn.", "Yr ail ateb mwyaf cyffredin oedd ‘Pe bawn i’n teimlo’n fwy hyderus’, gyda 117 o ddisgyblion yn ei ddewis, ymhlith disgyblion yn yr ysgol gyfan.",
     "“Nesaf roedd …” (Next came) vs the engine's ordinal (row 10); the quoted label is the survey's “Pe bawn i’n …” vs the translator's own “Roeddwn i’n …” (AW-1); “yn dewis yr ateb hwn” vs “yn ei ddewis”.", V_ENGINE, "Rows 10 and AW-1."),
    (14, "… dywedodd y grŵp mwyaf (173, neu 47%) ‘Weithiau’.", "… ‘Weithiau’ oedd yr ateb a ddewiswyd amlaf (173, neu 47%).", "As row 1 (c).", V_ENGINE, "As row 1."),
    (15, "… dywedodd y grŵp mwyaf (186, neu 51%) ‘Ydw, weithiau’.", "… ‘Ydw, weithiau’ oedd yr ateb a ddewiswyd amlaf (186, neu 51%).", "As row 1 (c).", V_ENGINE, "As row 1."),
    (16, "Nesaf roedd Saethyddiaeth ac Eira-fyrddio yn gyfartal, a ddewiswyd 69 tro yr un, ar draws yr ysgol gyfan.", "Yna daeth saethyddiaeth ac eirafyrddio, gyda 69 o ddewisiadau yr un, ymhlith disgyblion yn yr ysgol gyfan.",
     "“Nesaf roedd” vs “Yna daeth”; “a ddewiswyd 69 tro yr un” (chosen 69 times each) vs “gyda 69 o ddewisiadau yr un” (with 69 selections each); casing of sport names; “Eira-fyrddio” vs “eirafyrddio” (spelling of the label).", V_ENGINE, "Sheet 5 comparison; spelling to the term list."),
    (17, "Roedd Dodgeball yn arwain ymhlith bechgyn (a ddewiswyd 46 tro), ac arweiniodd Sglefrio Iâ ymhlith merched (fe’i dewiswyd 47 tro), ar draws yr ysgol gyfan.", "Pêl osgoi oedd ar y brig ymhlith bechgyn (46 o ddewisiadau), tra bo sglefrio iâ ar y brig ymhlith merched (47 o ddewisiadau), yn yr ysgol gyfan.",
     "“Dodgeball” left in English by the translator vs the survey's Welsh label “Pêl osgoi”; “yn arwain / arweiniodd” (led) vs the attested “ar y brig” (SYN-08 contrast pattern with tra bo); “a ddewiswyd 46 tro” vs “46 o ddewisiadau”.", V_ENGINE, "Sheet 5; the sport name is the survey's label (query sheet AW-1 principle)."),
    (18, "Dodgeball oedd y prif gamp â galw heb ei fodloni amdani a ddewiswyd amlaf gan fechgyn …", "Pêl osgoi oedd y gamp gyntaf a ddewiswyd amlaf fel camp yr oedd galw amdani heb ei fodloni ymhlith bechgyn …",
     "“y prif gamp” (the main sport) vs the engine's ordinal “y gamp gyntaf” (the first …) for “the first most frequently selected”; both keep the feminine agreement “amdani”.", V_ENGINE, "Sheet 5; ordinal rendering of “first/second most …” is sheet 4 rule 15."),
    (19, "Dodgeball oedd â’r nifer fwyaf ar gyfer galw heb ei fodloni (81 disgybl), a Tennis oedd â’r nifer fwyaf yn cymryd rhan yn bresennol (273) …", "Pêl osgoi oedd â’r galw mwyaf heb ei fodloni (81 disgybl), tra bo tennis â’r cyfranogiad presennol uchaf (273), …",
     "“â’r nifer fwyaf ar gyfer galw” (the largest number for demand) vs “â’r galw mwyaf” (the largest demand); “a Tennis oedd …” vs the contrast “tra bo tennis …” (SYN-08, D12).", V_ENGINE, "Sheet 4 rule 5 (tra bo) and sheet 5."),
]
